### ISSUE TITLE
There is no instantiate_lrscheduler_from_config function in vidtok.modules.util.

### ISSUE THREAD

**Issue by HuaizeLiu** [microsoft/VidTok#7]
![Image](https://github.com/user-attachments/assets/0bfb1207-0168-4be0-b7c3-b784f74f1a12)

There is no instantiate_lrscheduler_from_config function in vidtok.modules.util.

**Comment by wangyuchi369** [comment]
Hi, you can manually add these codes to `vidtok/modules/util.py`, and we will update our code accordingly. Thank you for raising this issue.
```
from torch.optim.lr_scheduler import _LRScheduler, LambdaLR, StepLR

def instantiate_lrscheduler_from_config(optimizer, config, name='main-LR'):
    assert 'target' in config, 'Expected key `target` to instantiate.'
    if ('torch.optim' in config.target) or ('timm.scheduler' in config.target):
        scheduler = get_obj_from_str(config["target"])(optimizer, **config.get("params", dict()))
        lr_scheduler = {
            'scheduler': scheduler,
            'name': name
            }
    else:
        scheduler_init = instantiate_from_config(config)
        scheduler = LambdaLR(optimizer, lr_lambda=scheduler_init.schedule)
        lr_scheduler = {
            'scheduler': LambdaLR(optimizer, lr_lambda=scheduler_init.schedule),
            'name': name,
            'interval': 'step',
            'frequency': 1
            }
    return scheduler
```

**Comment by HuaizeLiu** [comment]
Thank you very much for your reply. I have another question: there is no ImageLogger class in vidtok.modules.logger.

**Comment by HuaizeLiu** [comment]
![Image](https://github.com/user-attachments/assets/e85af6ba-6780-4119-9027-cb019f3a1a97)
in configs/vidtwin/vidtwin_structure_7_7_8_dynamics_7_8.yaml

**Comment by wangyuchi369** [comment]
Thank you for the reminder. You can simply use the logger from other YAML files in VidTok, like this:
```
  callbacks:
    image_logger:
      target: vidtok.modules.logger.ImageVideoLogger
      params:
        disabled: false
        rescale: true
        enable_autocast: false
        batch_frequency: 5000
        max_samples: 2
        increase_log_steps: false
        log_first_step: false
        log_before_first_step: false
        log_images_kwargs:
          n_rows: 16
```
